export const emotionsProperties=[{code:1, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:2, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:3, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:4, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:5, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:6, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:7, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:8, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:9, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:10, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:11, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:12, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:13, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
{code:14, material:{music:[], video:[], exersice:[],  articles:[], description:''}},
]