export const emotions=[{code:"anger", label:'Гнев', effect:'negative ', color:'orange', ico:''}, 
{code:'sadness', label:'Грусть', effect:'negative ', color:'blue', ico:''}, 
{code:'apathy', label:'Апатия', effect:'negative ', color:'slate', ico:''},
{code:'loneliness', label:'Одиночество', effect:'negative ', color:'indigo', ico:''},
{code:'anxiety', label:'Тревога', effect:'negative ', color:'teal', ico:''},
{code:'fear' , label:'Страх', effect:'negative ', color:'vielet', ico:''},
{code:'stress', label:'Стресс', effect:'negative ', color:'purple', ico:''},
{code:'panic', label:'Паника', effect:'negative ', color:'rose', ico:''},
//позитивные
{code:'joy', label:'Радость', effect:'positive ', color:'yellow', ico:''},
{code:'love', label:'Любовь', effect:'positive ', color:'pink', ico:''},
{code:'inspiration', label:'Вдохновение', effect:'positive ', color:'cyan', ico:''},
{code:'calmness', label:'Спокойствие', effect:'positive ', color:'lime', ico:''},
{code:'gratitude', label:'Благодарность', effect:'positive ', color:'green', ico:''},
{code:'confidence', label:'Увереность', effect:'positive ', color:'emerald', ico:''},
]